apiVersion: v1
kind: Service
metadata:
  name: nginx-mindfactory-service-nodeport
spec:
  type: NodePort
  selector:
    app: nginx-mindfactory
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080